# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do
  lane :beta do
    sync_code_signing(
      git_url: "https://github.com/devxoul/certificates",
      type: "appstore",
    )
    build_app(
      scheme: "Drrrible",
      export_xcargs: "-allowProvisioningUpdates",
    )
    upload_symbols_to_crashlytics(
      dsym_path: "./Drrrible.app.dSYM.zip",
      api_token: "60d029a7c4e10e88538e507f1afbdf24583030ac",
      binary_path: "./Pods/Crashlytics/iOS/Crashlytics.framework/uploadDSYM",
      platform: "ios"
    )
    upload_to_testflight(changelog: "Improvements and bug fixes")
  end

  lane :appstore do
    upload_to_app_store(
      force: true,
      skip_binary_upload: true,
      skip_screenshots: true,
      automatic_release: true,
      submit_for_review: true,
      submission_information: {
        add_id_info_uses_idfa: false,
        add_id_info_serves_ads: false,
        add_id_info_tracks_install: false,
        add_id_info_tracks_action: false,
        add_id_info_limits_tracking: false,
        export_compliance_uses_encryption: false,
      }
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
